Changes in connect function
emc-isilon/pike pull request #130
Opened 2023-04-27 04:33 UTC by isi-adas

---Added retry in connect call to deal with sudden network issues

2023-04-27 16:48 UTC, masenf requested changes
do you have plans to forward port this change?

2023-04-27 16:48 UTC, masenf commented on pike/model.py
> +import polling2
i think you need to add `polling2` to the `install_requires` in `setup.cfg`  if you're going to import it here.

2023-04-27 17:16 UTC, isi-adas commented
> do you have plans to forward port this change?

I think there is no issues with forward porting this change. I will unless any concerns.

2023-04-28 03:10 UTC, jtmoon79 reviewed
Hi Arnab! 😄 

nitpick: Why not use the same variable name as the `polling`? e.g. `retry_limit` should be `max_tries`.  Seems silly that the same variable should be given such different names.

Otherwise, LGTM

2023-04-28 04:02 UTC, masenf commented
That's a great call out, thanks @jtmoon79 and good to see you 👋.

I think the variable names should not be arbitrarily different.

2023-04-28 14:58 UTC, isi-adas commented
Hey @jtmoon79 how is it going...Thanks for the callout. I will update.

2023-04-28 20:34 UTC, masenf approved these changes

2023-04-28 20:34 UTC, merged