Added decoding support for FSCTL_QUERY_NETWORK_INTERFACE_INFO
emc-isilon/pike pull request #131
Opened 2023-05-31 18:36 UTC by sudosantanu

2023-06-01 15:29 UTC, isi-adas commented
cc: @isi-rszczesniak , @marchhare09

2023-06-02 01:53 UTC, isi-adas commented on src/pike/smb2.py
> +        self.next_loc ={}
Spacing needs consistency on both sides of `=`.

2023-06-02 01:53 UTC, isi-adas commented on src/pike/smb2.py
> +                self.next_loc[i] = cur.decode_uint32le()
Indentations would be good to be 4 spaces.

2023-06-02 01:53 UTC, isi-adas commented on src/pike/smb2.py
> +                i = i+1
Spaces around `+`.

2023-06-02 01:53 UTC, isi-adas commented on src/pike/smb2.py
> +        self.reserved_3 = {}
Would it be nice or correct to move this entire chunk to __init__() ?

2023-06-02 15:52 UTC, isi-adas approved these changes

2023-06-02 17:51 UTC, masenf requested changes
This should be following MS-SMB2 structure descriptions.

You need a [SockaddrStorage structure](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/4b77102f-769f-414d-b137-47cabfe8be8f) that contains the IP fields.

You need a [NetworkInterfaceInfo](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/fcd862d1-1b85-42df-92b1-e103199f531f) frame that contains the other fields and references the sockaddr storage.

Finally, the QueryNetworkInterfaceInfoResponse should contain one or more NetworkInterfaceInfo objects as children.

If you're just wanting to hack it like this, I recommend implementing that in your test code, not in the upstream. This project aims to be as close to the protocol specification as possible.

2023-06-02 17:51 UTC, masenf commented on src/pike/smb2.py
> +        while True :
This class is the correct place to loop through all of the structures in the buffer... but these structures need to be stored as **separate objects**, not indexed into several dictionaries with the same key. No other structure in pike uses this style.

2023-06-15 17:30 UTC, masenf requested changes
a few formatting changes are requested.

thanks for restructuring the decode in the pike style! that part looks great.

2023-06-15 17:30 UTC, masenf commented on src/pike/smb2.py
> +        reserved = array.array("B", [0] * 8)
```suggestion
        self.port = array.array("B", [0] * 2)
        self.ip = array.array("B", [0] * 4)
        self.reserved = array.array("B", [0] * 8) 
```

2023-06-15 17:30 UTC, masenf commented on src/pike/smb2.py
> +        scopeid = array.array("B", [0] * 4)
```suggestion
        self.port = array.array("B", [0] * 2)
        self.flowinfo = array.array("B", [0] * 4)
        self.ip = array.array("B", [0] * 16)
        self.scopeid = array.array("B", [0] * 4)
```

2023-06-15 17:30 UTC, masenf commented on src/pike/smb2.py
> +        if self.family == IPv4 :
```suggestion
        if self.family == IPv4:
```

2023-06-15 17:30 UTC, masenf commented on src/pike/smb2.py
> +        elif self.family == IPv6 :
```suggestion
        elif self.family == IPv6:
```

2023-06-15 17:30 UTC, masenf commented on src/pike/smb2.py
> +        core.Frame.__init__(self, parent)
```suggestion
        super().__init__(parent)
```

2023-06-15 17:30 UTC, masenf commented on src/pike/smb2.py
> +        while True :
```suggestion
        while True:
```

2023-06-15 17:30 UTC, masenf commented on src/pike/smb2.py
> +                self.family= AddressFamily.IPv6
```suggestion
                self.family = AddressFamily.IPv6 
```

2023-06-15 17:30 UTC, masenf commented on src/pike/smb2.py
> +        core.Frame.__init__(self, parent)
```suggestion
        super().__init__(parent)
```

2023-06-15 17:30 UTC, masenf commented on src/pike/smb2.py
> +        self.reserved = []
the types for these initial values seem a bit weird.

i would expect them to be initialized to an empty SockaddrIn and empty byte array.

2023-06-16 17:29 UTC, masenf requested changes
i forgot that we still support 2.7, which doesn't have `super()`, my bad.

2023-06-16 17:29 UTC, masenf commented on src/pike/smb2.py
> +        super().__init__(self, parent)
```suggestion
        core.Frame.__init__(self, parent)
```

2023-06-16 17:29 UTC, masenf commented on src/pike/smb2.py
> +        super().__init__(self, parent)
```suggestion
        core.Frame.__init__(self, parent)
```

2023-06-16 17:53 UTC, masenf reviewed
more py27 isms

2023-06-17 00:15 UTC, masenf commented
The actual import error on py27 is

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/pike/.tox/py27/lib64/python2.7/site-packages/pike/__init__.py", line 31, in <module>
    from pike.test import TreeConnect as TreeConnect
  File "/workspace/pike/.tox/py27/lib64/python2.7/site-packages/pike/test/__init__.py", line 33, in <module>
    import pike.model as model
  File "/workspace/pike/.tox/py27/lib64/python2.7/site-packages/pike/model.py", line 51, in <module>
    from . import crypto
  File "/workspace/pike/.tox/py27/lib64/python2.7/site-packages/pike/crypto.py", line 32, in <module>
    from . import smb2
  File "/workspace/pike/.tox/py27/lib64/python2.7/site-packages/pike/smb2.py", line 35, in <module>
    import ipaddress
ImportError: No module named ipaddress
```

ipaddress isn't a module on py27 😔

will need to install the backport if this functionality is really needed.

2023-06-19 17:19 UTC, isi-adas approved these changes
LGTM, subject to passing CI.
Likely dependent on https://github.com/emc-isilon/pike/pull/132

2023-06-19 17:47 UTC, sudosantanu commented on src/pike/smb2.py
> +        self.ip = ':'.join(str(ip_hex_raw[i:i+4]) for i in range(0, len(ip_hex_raw), 4))
yes... we were not testing it initially, if tested we would have gotten error. This one can be done using  binascii.
Something like:
ip_hex = binascii.hexlify(cur).decode('utf-8')
self.ip  = ':'.join(ip_hex[i:i+4] for i in range(0, len(ip_hex), 4))

to keep the parity with IPV4, I did the IPv6 this way.

2023-06-19 23:58 UTC, masenf commented
Rebased on master and cleaned up whitespace

2023-06-20 01:40 UTC, isi-adas approved these changes

2023-06-20 16:56 UTC, merged